# Generated by Django 4.1.3 on 2022-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
